Added dependencies and routes
dump-hr/internship-app pull request #33
Opened 2023-09-17 10:57 UTC by dbaric99

- Closes: #3

2023-09-27 16:50 UTC, fdoljanin requested changes
Kako imamo malo vremena ne očekujem da sad sve rewriteaš, ali za početak bih bar ovo napravio:
- na filter mi se ne događa ništa, ali svakako mislim da su potrebne tu dvije opcije:
1. intervjuisti: highlight termine na kojem se pojavljuju bar neki od tih intervjuera
2. područja: highlight termine na kojem je zadovoljena potreba za tim područjem tj. kombinacijom (kako smo to 
definirali, možeš vidjeti u Bartolovoj implementaciji prikaza termina pripravniku)
- bojanje intervju termina ovisno o statusu; može biti  slobodan, pending,  done, missed
- NI SLUČAJNO BRISATI INTERVJUE NA KOJE SE NEKI PRIPRAVNIK ZAPISAO! potrebna je ta provjera
- ne overwriteati druge intervjue, ako se clashaju kad selektiraš po kalendaru, ostavi stare
- ne slati milijun requestova, jedini requestovi koji su nam potrebni: GET: 1. popis intervjuista 2. popis slotova POST: svi novi intervjui DELETE: individualni intervju (i provjere i na FE i na BE da se neko ne zezne)
- dakle, kad napravimo nove termine, nek se lista novih termina ispiše sa strane i tek klikom na SAVE se šalju svi novi na backend

Osim ovoga, ne odobravam dok ne popraviš sva eslint upozorenja. Koristimo TS s razlogom!

2023-09-27 16:50 UTC, fdoljanin commented on apps/api/src/interview-slot/interview-slot.controller.ts
> +  async createInterviewSlot(@Body() interviewSlotDto: CreateInterviewSlotDto) {
ovo bih isto rado da imamo botun SAVE u aplikaciji pa pošalje sve nove intervjue kao array, a ne 200 requestova pravit

2023-09-27 16:50 UTC, fdoljanin commented on apps/api/src/interview-slot/interview-slot.controller.ts
> +  async createInterviewSlot(@Body() interviewSlotDto: CreateInterviewSlotDto) {
također, volio bih da su novi intervjui u tom slučaju prije nego se klikne SAVE uokvireni i da imamo negdje ispisano koliko je novih intervjua i kakvih

2023-09-27 16:50 UTC, fdoljanin commented on apps/api/src/interview-slot/interview-slot.controller.ts
> +  async createInterviewSlot(@Body() interviewSlotDto: CreateInterviewSlotDto) {
ovako dodaš i ne znaš što se promijenilo

2023-09-27 16:50 UTC, fdoljanin commented on apps/api/src/interview-member-participation/dto/createInterviewMemberParticipation.dto.ts
> +  interviewrId: string;
typo
i msm da je ovo moglo bit dio interview slot foldera

2023-09-27 16:50 UTC, fdoljanin commented on apps/api/src/interviewer/interviewer.controller.ts
> +  findByDiscipline(@Param('discipline') discipline: string) {
čak mi ovo s filterom intervjuera po disciplini nije baza, msm mogla si ovo normalno filtrirat na frontendu a ne pravit request, ali i svakako sami znamo kojeg su nam područja članovi

2023-09-27 16:50 UTC, fdoljanin commented on apps/api/.env
> +DATABASE_URL=postgresql://postgres:0000@localhost:5432/internship-app
y

2023-09-27 16:50 UTC, fdoljanin commented on apps/web/src/components/Calendar/Calendar.tsx
> +    overlappingEvents.forEach(deleteEvent);
umjesto da brišeš postojeće eventove, bolje da jednostavno ne pošalješ na backend ove nove. ako je overlap, bolje da ih mi ručno brišemo - ovako se neko zezne i propadnu intervjui

2023-09-27 16:50 UTC, fdoljanin commented on apps/web/src/components/Calendar/Calendar.tsx
> +    overlappingEvents.forEach(deleteEvent);
osim toga ovo je async, opreznije treba s tim

2023-09-27 16:50 UTC, fdoljanin commented on apps/web/src/components/Calendar/Calendar.tsx
> +  }, [existingEvents]);
hm

2023-09-27 16:50 UTC, fdoljanin commented on apps/web/src/components/Calendar/Calendar.tsx
> +                eventDeleteHandler={deleteEvent}
ts

2023-09-27 16:50 UTC, fdoljanin commented on apps/web/src/App.tsx
> +import { AdminInterviewPage } from './pages/AdminInterviewPage/AdminInterviewPage';
eslint

2023-10-01 13:53 UTC, fdoljanin requested changes
Dosta bolje nego prošli put, brv:) još popravi da docker build ne vraća error, općenito ne možemo odobriti dok ima errora i warninga

2023-10-01 13:53 UTC, fdoljanin commented on apps/web/src/components/Calendar/Calendar.tsx
> +          },
Property 'children' does not exist on type 'EventWrapperProps<object>'

2023-10-01 13:53 UTC, fdoljanin commented on apps/web/src/constants/paths.ts
> +  AdminInterviewPicker = '/interview-picker',
samo molim te promijeni da ima u ruti /admin, i možda /admin/interivew-scheduler

2023-10-01 13:53 UTC, fdoljanin commented on apps/web/src/constants/paths.ts
> +  AdminInterviewPicker = '/interview-picker',
i to dodaj gore među admin putanje

2023-10-01 13:53 UTC, fdoljanin commented on apps/api/src/interview-slot/interview-slot.controller.ts
> +  @Post()
trebat će dodat ovdje autorizaciju btw

2023-10-01 13:53 UTC, fdoljanin commented on apps/api/src/interview-slot/interview-slot.service.ts
> +        intern: true,
nebitno, al šta nije da je internid svakako ukljucen, a ovo null dok nije includeano, a ovo ne koristiš?

2023-10-01 13:53 UTC, fdoljanin commented on apps/api/src/interview-slot/interview-slot.service.ts
> +        intern: true,
ok nebitno, al interna ne koristiš, a internId je svakako uključen

2023-10-01 13:53 UTC, fdoljanin commented on apps/api/src/interview-slot/interview-slot.service.ts
> +    if (interviewToDelete.internId) return;
vrati neki exception tipa BadRequestException('Cannot delete interview with intern on it! Try cancelling interview first'), pa ga prikaži s toast.error

2023-10-01 13:53 UTC, fdoljanin commented on apps/api/src/interview-slot/interview-slot.service.ts
> +          answers: JSON.stringify({}),
makni stringify, nije string nego json format

2023-10-01 13:53 UTC, fdoljanin commented on apps/api/src/interview-slot/interview-slot.service.ts
> +        await this.prisma.interviewMemberParticipation.create({
cisto za ubuduce, mogla si unutar slot.create dodati odmah intervjuiste pomocu createmany i mapirati ih, cak i slotove kreirati pomoću createmany, al i ovo je okej, samo je problem ako jedan faila šta je s drugima nije baš jasno

2023-10-01 13:53 UTC, fdoljanin commented on apps/web/src/components/Calendar/Calendar.tsx
> +export const Calendar: React.FC<Props> = ({
ovo je doduše InterviewCalendar jer je za njega specifičan, al nmvz

2023-10-01 13:53 UTC, fdoljanin commented on packages/types/src/intern.ts
> +
naziv Event je zavaravajuć, samo nekako drugačije da je jasno da se radi o intervjuu

2023-10-01 13:53 UTC, fdoljanin commented on apps/web/src/pages/AdminInterviewPage/AdminInterviewPage.tsx
> +    useFetchInterviewSlots(null);
err

2023-10-01 13:53 UTC, fdoljanin commented on apps/web/src/pages/AdminInterviewPage/AdminInterviewPage.tsx
> +    useFetchInterviewSlots(null);
crveno

2023-10-01 13:53 UTC, fdoljanin commented on apps/web/src/pages/AdminInterviewPage/AdminInterviewPage.tsx
> +      return;
vrati error toast da moraju biti selektirani intervjuisti, ovako će se neko zbunit (npr ja xD)

2023-10-01 13:53 UTC, fdoljanin commented on apps/web/src/pages/AdminInterviewPage/AdminInterviewPage.tsx
> +  }, [events, interviewerFilter]);
sad može proć, al za inače, bolje ne koristit state za vrijednosti koje se mogu jednoznačno izračunat iz drugih stateova

2023-10-01 13:53 UTC, fdoljanin commented on apps/web/src/components/CalendarSidebar/CalendarSidebar.tsx
> +  setInterviewers: (value: string[] | null) => void;
možeš jednostavno koristiti tip koji je od setStatea, dakle react dispatch

2023-10-01 13:53 UTC, fdoljanin commented on apps/web/src/components/CalendarSidebar/CalendarSidebar.tsx
> +}
možeš svima njima jednostavno koristiti tip koji je od setStatea, dakle react dispatch

2023-10-01 13:53 UTC, fdoljanin commented on apps/web/src/components/Calendar/Calendar.tsx
> +    if (overlappingEvents.length > 0) return;
vrati toast error s upozorenjem da nije dozvoljeno preklapanje

2023-10-01 13:53 UTC, fdoljanin commented on apps/web/src/helpers/calendarHelper.ts
> +      moment(e.end).isBetween(newEvent.start, newEvent.end);
inače, ako se periodi `a` i `b` ne preklapaju, onda sigurno vrijedi
`a.start > b.end || b.start > a.end` (odnosno >=, ovisi kako želiš), jer jedan mora počet nakon drugog:D
pa ubuduće možeš tako lakše

2023-10-01 13:55 UTC, fdoljanin requested changes
github pr extension being buggy

2023-10-01 13:55 UTC, fdoljanin requested changes
Dosta bolje nego prošli put, brv:) još popravi da docker build ne vraća error, općenito ne možemo odobriti dok ima errora i warninga. što se tiče UI, pojačaj bojicu da se na prvu jasnije da je slot zauzet, i ne bi bilo loše da se klikom na pending slot otvori interview page (ili da bar negdje piše ime) jer moraju nekako znat intervjuisti tko je na redu

2023-10-02 23:03 UTC, bdeak4 requested changes
generalno super sve radi, samo par stvari bi trebalo popravit

- ~~nekako bolje oznacit da su ova 2 inputa za dodavanje a ovo gore filter jer me bas bas zbunilo~~
![image](https://github.com/dump-hr/internship-app/assets/32748145/d214b3f4-7af3-40bf-a9c4-6a4e1b66ac90)


- ~~dodat admin header koji se nalazi na svim screenovima i dodat ovaj screen u navigaciju~~

2023-10-02 23:03 UTC, bdeak4 commented on apps/web/src/api/useFetchInterviewers.tsx
> +  return useQuery(['interviewers'], () => {
ovaj endpoint mi baca 404 lokalno (mozda je nesto do mene) rjesenje je `/interviewers` -> `/interviewer`

2023-10-02 23:03 UTC, bdeak4 commented on apps/web/src/components/Calendar/Calendar.tsx
> +  const [events, setEvents] = useState(existingEvents);
nez jel nesto propustam al zasto se ne koristi samo `existingEvents` umjesto events statea koji prati ovaj

2023-10-02 23:03 UTC, bdeak4 commented on apps/web/src/pages/AdminInterviewPage/AdminInterviewPage.tsx
> +      return;
+1

2023-10-03 16:34 UTC, fdoljanin commented on apps/web/src/api/useFetchInterviewers.tsx
> +  return useQuery(['interviewers'], () => {
+1

2023-10-03 16:36 UTC, fdoljanin commented on apps/web/src/pages/AdminInterviewPage/AdminInterviewPage.tsx
> +      return;
@dbaric99

2023-10-03 16:37 UTC, fdoljanin commented on apps/web/src/pages/AdminInterviewPage/AdminInterviewPage.tsx
> +    if (!interviewSlots || !interviewSlots.every((slot) => slot.interviewers)) {
ovo nema smisla jer ionako se prazni intervjui ne šalju na backend, a ovi interviewSlots su iz baze. samo stavi toast na onom mjestu gore gdje smo komentirali

2023-10-03 16:40 UTC, fdoljanin commented on apps/web/src/pages/AdminInterviewPage/AdminInterviewPage.tsx
> +        return undefined as unknown as MappedEvent;
rly

2023-10-03 22:30 UTC, bdeak4 commented on apps/api/src/interview-slot/interview-slot.service.ts
> +        await this.prisma.interviewMemberParticipation.create({
+1, definitivno treba zawrappat ovo u transakciju
https://www.prisma.io/docs/concepts/components/prisma-client/transactions#interactive-transactions

2023-10-04 16:20 UTC, fdoljanin commented on apps/web/src/components/Calendar/Calendar.tsx
> +  }, [existingEvents]);
@dbaric99 amo

2023-10-04 16:42 UTC, fdoljanin commented on apps/web/src/components/Calendar/EventContent.tsx
> +        </div>
ovo makni za intervjue koji imaju na sebi pripravnika, pa mozda na klik ove komponente da se otvori /admin/interview/id-pripravnika ako je incoming ili /admin/intern/id-pripravnika ako je intervju prošao! :)

2023-10-06 07:40 UTC, bdeak4 approved these changes

2023-10-06 07:41 UTC, merged